### ISSUE TITLE
[Errno 13] Permission denied with JIRA options

### ISSUE THREAD

**Issue by gemygk** [EI-CoreBioinformatics/eirepeat#1]
Bug reported by colleague Jon Wright:

`eirepeat run` command fails when the JIRA password file is inaccessible
```
PermissionError in line 34 of /ei/software/cb/eirepeat/1.1.0/x86_64/lib/python3.9/site-packages/eirepeat/workflow/Snakefile:
[Errno 13] Permission denied: '/ei/cb/common/.jira_pwd'
  File "/ei/software/cb/eirepeat/1.1.0/x86_64/lib/python3.9/site-packages/eirepeat/workflow/Snakefile", line 34, in <module>
  File "/ei/software/cb/python_miniconda/4.11.0_py3.9_eirepeat/x86_64/lib/python3.9/pathlib.py", line 1456, in is_file
  File "/ei/software/cb/python_miniconda/4.11.0_py3.9_eirepeat/x86_64/lib/python3.9/pathlib.py", line 1232, in stat
Traceback (most recent call last):
  File "/ei/software/cb/eirepeat/1.1.0/x86_64/bin/eirepeat", line 8, in <module>
    sys.exit(main())
  File "/ei/software/cb/eirepeat/1.1.0/x86_64/lib/python3.9/site-packages/eirepeat/__main__.py", line 264, in main
    args.handler(args)
  File "/ei/software/cb/eirepeat/1.1.0/x86_64/lib/python3.9/site-packages/eirepeat/__main__.py", line 59, in command_run
    EIRepeat(args).run()
  File "/ei/software/cb/eirepeat/1.1.0/x86_64/lib/python3.9/site-packages/eirepeat/__main__.py", line 124, in run
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command 'snakemake --snakefile /ei/software/cb/eirepeat/1.1.0/x86_64/lib/python3.9/site-packages/eirepeat/workflow/Snakefile --configfile run2/run_config.yaml --latency-wait 120 --jobs 100 --cluster-config /ei/software/cb/eirepeat/1.1.0/x86_64/lib/python3.9/site-packages/eirepeat/etc/hpc_config.json --config notify=False verbose=False --drmaa ' -p {cluster.partition} -c {cluster.cores} --mem={cluster.memory} -J {cluster.J} -o /scratch/wrightj/foxtail/repeatmasker/run2/logs/{rule}.%N.%j.cluster.log' --printshellcmds --reason ' returned non-zero exit status 1.
```

**Comment by gemygk** [comment]
Fixed in 58288cbbef004ac0f99fcb181f61a1757cde8410
